### ISSUE TITLE
add https_proxy/http_proxy env var support

### ISSUE THREAD

**Issue by luisr-escobar** [keptn-contrib/dynatrace-service#180]
Container image is missing packages needed to allow alpine linux to connect outside the cluster using an http proxy.

Adding the following packages to the Dockerfile and rebuilding image fixed the problem.

`apk add curl netcat-openbsd`

**Comment by luisescobar89** [comment]
This is an scenario where the k8s cluster is deployed on prem and the pods need to connect to the dynatrace saas tenant via a proxy.

First thing is we need to add the required packages to the existing Dockerfile on this repo to allow the base OS to connect to a proxy:

```
apk add curl netcat-openbsd 
```

Then build the image:

```
docker build -t dynatrace-service:x.x.x
```

Next on the deployment file (deploy/service.yaml) the following environment variables need to be added:

```
- name: http_proxy
value: http://proxy.domain.com
- name: https_proxy
value: http://proxy.domain.com
- name: no_proxy
value:.example.com
```

After these settings are configured, the pod will attempt to connect to anything that is not in the example.com domain through the proxy defined on the http_proxy env vars.

**Comment by agrimmer** [comment]
Related to https://github.com/keptn-contrib/dynatrace-sli-service/issues/74

**Comment by christian-kreuzberger-dtx** [comment]
Thank you for explaining the details.

For this use-case it makes perfect sense to include those dependencies and the configuration. I believe that other Keptn microservices might have similar use-cases (e.g., accessing a repo with Helm Charts behind a proxy, or accessing a prometheus server behind a proxy, Git Repo, literally anything that's not in the cluster might only be reachable with a proxy). 

If we include the dependencies and the configuration option in each Keptn microservice (and to be honest, we can only ensure that for Keptn core services, 3rd party services would have to do it in their own), we would generate a lot of configuration overhead for the administrator of the Keptn cluster.

I am wondering if instead we can use a more generic approach, such as Kubernetes NetworkPolicy (e.g., using istio egress). This would solve the problem for all services at once (and gives you much more flexibility).

Example: https://istio.io/latest/docs/tasks/traffic-management/egress/http-proxy/#configure-traffic-to-external-https-proxy

@agrimmer what's your take on this?

**Comment by agrimmer** [comment]
I also would like to prevent adding the external dependency `netcat-openbsd` because as @christian-kreuzberger-dtx explained, it produces lots of overhead.
Furthermore, I am unsure whether Keptn should be responsible for setting up k8s NetworkPolicies because only the network admin knows what is needed.
I am looping in @thschue for his opinion on this.

**Comment by thschue** [comment]
As I think that this feature will be needed in enterprise environments and other solutions (such as the netcat thing) would be a bit hacky, I would propose to implement proxy handling in the Dynatrace Service (example: https://ipfs.io/ipfs/QmfYeDhGH9bZzihBUDEQbCbTc5k5FZKURMUoUvfmc27BwL/http/proxy_handling.html).

**Comment by christian-kreuzberger-dtx** [comment]
Okay, according to the link @thschue posted we would have to add
```
proxyURL, err := url.Parse(proxyString)
transport := &http.Transport{Proxy: http.ProxyURL(proxyURL)}
client := &http.Client{Transport: transport}
```
to our code and use this function
```
func ProxyFromEnvironment(req *Request) (*url.URL, error)
```
to read proxy information from an environment variable `HTTP_PROXY`.

Finally, we will need to support authentication mechanisms with that proxy (e.g., Basic Auth), as well as SSL certificates (or rather the fact that certificate verification needs to be disabled for the proxy).

Proposal for enviornment variables to introduce:

* `HTTP_PROXY` (e.g., http://some-server:port/proxy-url/)
* `HTTP_PROXY_USER` (default: empty)
* `HTTP_PROXY_PASSWORD` (default: empty)
* `HTTP_PROXY_SSL_VERIFY`(default: true)
* `HTTP_SSL_VERIFY` (default: true)

**Comment by agrimmer** [comment]
We at least have to provide a flag for disabling the SSL verification.

**Comment by arthurpitman** [comment]
I will take this issue

**Comment by christian-kreuzberger-dtx** [comment]
Please consider the Harbor Helm Chart for adding values regarding proxy configuration:
https://github.com/goharbor/harbor-helm/blob/2a1742269ea4e1e7e68587c3c753896264fa582f/values.yaml#L349-L354

**Comment by christian-kreuzberger-dtx** [comment]
According to https://www.oreilly.com/library/view/security-with-go/9781788627917/5ea6a02b-3d96-44b1-ad3c-6ab60fcbbe4f.xhtml
we do not need to implement anything in Go. Go's default HTTP client should respect the environment variables `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY`.

@donovanmuller can you confirm that?

**Comment by donovanmuller** [comment]
@christian-kreuzberger-dtx Based on setting only the environment variables mentioned on the `configuration-service`, yes, that's all that was required.

**Comment by luisr-escobar** [comment]
@donovanmuller so all that needs to be done is set the proxy env vars under these line [L69](https://github.com/keptn-contrib/dynatrace-service/blob/release-0.12.0/deploy/service.yaml#L69)? Was this tested on version 0.12.0?

**Comment by donovanmuller** [comment]
@luisr-escobar Correct, this is copied from my `configuration-service` live Pod manifest:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-service
  namespace: keptn
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: keptn
      app.kubernetes.io/name: configuration-service
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - env:
        - name: HTTP_PROXY
          value: http://proxy.com:3128
        - name: HTTPS_PROXY
          value: http://proxy.com:3128
        - name: NO_PROXY
          value: 172.20.0.1,example.com
        - name: PREFIX_PATH
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DATASTORE_URI
          value: mongodb-datastore:8080
        image: docker.io/keptn/configuration-service:0.8.2
        imagePullPolicy: IfNotPresent
...
```

I have note tried the the `dynatrace-service` at all.
