### ISSUE TITLE
Dynatrace-service crashes with custom sli.yaml

### ISSUE THREAD

**Issue by agrimmer** [keptn-contrib/dynatrace-service#515]
**Describe the bug**
When using these sli.yaml
```
---
spec_version: 0.1.4
indicators:
  trader-p90-response-time: MV2;MicroSecond;metricSelector=builtin:service.response.server:filter(and(in("dt.entity.service",entitySelector("type(service),tag(~"KeptnQualityGate~")")))):splitBy():percentile(90)
  trader-throughput: MV2;metricSelector=builtin:service.requestCount.total:filter(and(in("dt.entity.service",entitySelector("type(service),tag(~"KeptnQualityGate~")"))))
  apis-ui-v2-bootstrap-p90: MV2;MicroSecond;metricSelector=builtin:service.keyRequest.response.server:filter(and(in("dt.entity.service_method",entitySelector("type(service_method),entityName(~"/api/ui/v2/bootstrap~")")))):splitBy("dt.entity.service_method"):percentile(90)
```

the dynatrace-service crashes with
panic: runtime error: slice bounds out of range [:-1]

goroutine 119581 [running]:
github.com/keptn-contrib/dynatrace-service/internal/sli/query.extractMetricQueryFromMV2Query(0xc000488964, 0x94, 0xc0004e64a0, 0x19ff4e0, 0xc00058c000, 0xc0005c5908)
	/go/src/github.com/keptn-contrib/dynatrace-service/internal/sli/query/query_processing.go:178 +0xdb
github.com/keptn-contrib/dynatrace-service/internal/sli/query.(*Processing).executeMetricsV2Query(0xc0005c5e38, 0xc000488960, 0x94, 0x0, 0xed8f084f7, 0x0, 0x0, 0xed8f08bff, 0x0, 0xc000416160, ...)
	/go/src/github.com/keptn-contrib/dynatrace-service/internal/sli/query/query_processing.go:169 +0x3f
github.com/keptn-contrib/dynatrace-service/internal/sli/query.(*Processing).GetSLIValue(0xc0005c5e38, 0xc0001e64e0, 0x11, 0x1, 0x1, 0xc00058c770)
	/go/src/github.com/keptn-contrib/dynatrace-service/internal/sli/query/query_processing.go:64 +0x3e5
github.com/keptn-contrib/dynatrace-service/internal/sli.(*GetSLIEventHandler).retrieveMetrics(0xc00035c420, 0xc0005c5710, 0xc000218498)
	/go/src/github.com/keptn-contrib/dynatrace-service/internal/sli/get_sli_triggered_event_handler.go:300 +0x11f0
created by github.com/keptn-contrib/dynatrace-service/internal/sli.GetSLIEventHandler.HandleEvent
	/go/src/github.com/keptn-contrib/dynatrace-service/internal/sli/get_sli_triggered_event_handler.go:56 +0xca

**Versions**

Versions of the applicable components

* Dynatrace Service version : 0.17.0
* Dynatrace cluster version : ?
* Keptn version: 0.9.2

**Expected behavior**
If the SLI is invalid, the dynatrace-service should send a finished event with result=failed and the error message in field `message`.
