### ISSUE TITLE
Improve POD Configuration

### ISSUE THREAD

**Issue by heckelmann** [keptn-contrib/dynatrace-service#567]
For the pod dynatrace-service, the following setting is missing and has to be set:

- Resource limits
- Privileged is not set in container SecurityContext. Privileged defaults to 'false' but it should be explicitly set to 'false'.
- Seccomp annotation is missing
```
Seccomp can be specified like this:
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: test-container
```
