### ISSUE TITLE
Sync GH Workflows/Actions with what is currently available in keptn/gh-automation 

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-contrib/dynatrace-service#655]
To avoid duplicated code and make maintenance easier in the long run, actions and workflows from https://github.com/keptn/gh-automation/ should be used.

A good working example is provided in [keptn-contrib/prometheus-service](https://github.com/keptn-contrib/prometheus-service), but this is not a must-have, just an example :)

## Suggested Changes

- Split unit tests into a separate reusable action, e.g.: https://github.com/keptn-contrib/prometheus-service/tree/master/.github/actions/unit-tests
    **Usage Example**:
    ```
    ############################################################################
    # Unit tests                                                               #
    ############################################################################
    unit-tests:
      name: Unit Tests
      runs-on: ubuntu-20.04
      steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Unit tests
          uses: ./.github/actions/unit-tests

    ```
- Re-use validate-semantic PR workflow, e.g.:
    ```
    jobs:
      validate:
        uses: keptn/gh-automation/.github/workflows/validate-semantic-pr.yml@v1.3.0
        with:
          # Configure which scopes are allowed.
          scopes: |
            api
            core
            install
            cloudevents
            deps
            deps-dev
            distributor
            docs
            release
    ```
- Re-use docker-build action, e.g.:
    ```
          - name: Docker Build
            id: docker_build
            uses: keptn/gh-automation/.github/actions/docker-build@v1.3.0
            with:
              TAGS: |
                ${{ env.DOCKER_ORGANIZATION }}/${{ env.IMAGE }}:${{ env.VERSION }}
                ${{ env.DOCKER_ORGANIZATION }}/${{ env.IMAGE }}:${{ env.VERSION }}.${{ env.DATETIME }}
              BUILD_ARGS: |
                version=${{ env.VERSION }}
              REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
              REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
              PUSH: ${{(github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.pull_request.head.repo.full_name == github.repository)}}
    
          - id: report_docker_build_to_pr
            name: Report Docker Build to PR
            if: (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
            uses: marocchino/sticky-pull-request-comment@v2
            with:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              recreate: true
              header: test
              message: |
                The following Docker Images have been built:
                ${{ fromJSON(steps.docker_build.outputs.BUILD_METADATA)['image.name'] }}
    ```

@j-poecher @arthurpitman @Kavindu-Dodan please share your thoughts! If you want, I can create PRs for those suggestions. My goal is to not break your current workflows, but to reduce lines of codes and maintenance efforts (e.g., keptn/gh-automation actions/workflows will be maintained by Keptn core and Keptn ecosystem)

If you want to go one step further, I can also create a suggestion regarding the pre-release and release workflow, please send me a PM if you want that.
